[package]
name = "pixel-seed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.1"
draw = "0.3.0"
# Used by sha2
generic-array = "0.14.4"
hex = "0.4.3"
rand = "0.8.5"
sha2 = "0.10.6"
